name: .NET SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x

    - name: Install SonarScanner
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests and generate code coverage
      run: dotnet test --no-restore --configuration Release --collect:"XPlat Code Coverage"

    - name: Create coverage directory
      run: mkdir -p coverage

    - name: Move coverage file
      run: |
        REPORT_PATH=$(find . -name 'coverage.cobertura.xml')
        mv $REPORT_PATH coverage/

    - name: Begin SonarCloud analysis
      run: dotnet sonarscanner begin /k:"semester-3-backend" /o:"semester-3" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="coverage/coverage.cobertura.xml"
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

    - name: Build solution for analysis
      run: dotnet build --no-restore --configuration Release Travelblog.Core/Travelblog.Core.csproj

    - name: End SonarCloud analysis
      run: dotnet sonarscanner end
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
