name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.x' # Adjust this to your required .NET version

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release --no-restore

    - name: Run tests
      run: dotnet test --collect:"XPlat Code Coverage" --settings ./coverlet.runsettings --results-directory ./TestResults

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Generate code coverage report
      run: reportgenerator -reports:./TestResults/*/coverage.cobertura.xml -targetdir:./TestResults/Coverage -reporttypes:Html
      env:
        PATH: ${{ runner.tool_cache }}/.dotnet/tools:${{ env.PATH }}

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: ./TestResults/Coverage
