name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'

    - name: Install ReportGenerator
      run: dotnet tool install -g dotnet-reportgenerator-globaltool

    - name: Restore dependencies
      run: dotnet restore

    - name: Run tests and generate code coverage report
      run: dotnet test --collect:"XPlat Code Coverage" --results-directory:coverage

    - name: Generate Cobertura report
      run: reportgenerator -reports:coverage/*/coverage.cobertura.xml -targetdir:coverage -reporttypes:Cobertura

    - name: SonarCloud Begin
      run: dotnet sonarscanner begin /k:"semester-3-backend" /o:"semester-3" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vscoveragexml.reportsPaths="coverage/coverage.cobertura.xml"

    - name: Build project
      run: dotnet build

    - name: SonarCloud End
      run: dotnet sonarscanner end

    - name: Upload coverage report
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage
