name: "sonar_cloud_scan_github_actions"

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  DemoSonarCloudScan:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Run tests and generate coverage report
        run: |
          dotnet restore
          dotnet build --no-incremental
          dotnet-coverage collect "dotnet test" -f xml -o "coverage.xml"

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization=rekhugopal
            -Dsonar.projectKey=SonarCloudCodeAnalyisis
            -Dsonar.cs.vscoveragexml.reportsPaths=coverage.xml
            -Dsonar.inclusions=Travelblog.Api/**,Travelblog.Core/**,Travelblog.Dal/**
            -Dsonar.test.inclusions=Travelblog.Tests/**
            -Dsonar.exclusions=**/*.http,**/appsettings*.json,**/launchSettings.json
            -Dsonar.visualstudio.enable=false
            -Dsonar.modules=A67D0A79-B1E9-428E-A50A-66D79BAC5D7F,22016881-57E4-4C1E-B5F7-C685F26C96AC,67869C66-D085-43AA-901D-D4B50D2E7BB2,7A7A774D-D86C-4117-94E4-F5A6C32906F6
