name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.x'  # Install the .NET SDK 8.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build the solution
        run: dotnet build --no-restore
      
      - name: Run tests and collect coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage"
      
      - name: Install SonarScanner Global Tool
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: Begin SonarCloud Analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner begin /k:"semester-3-backend" /o:"semester-3" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml"
      
      - name: Build the solution (SonarCloud)
        run: dotnet build --no-incremental
      
      - name: End SonarCloud Analysis
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
