name: .NET Core

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'

    - name: Set up .NET Core
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Install dotnet tools
      run: dotnet tool install --global dotnet-sonarscanner

    - name: Install dotnet-coverage
      run: dotnet tool install --global dotnet-coverage

    - name: Remove sonar-project.properties if exists
      run: |
        if [ -f sonar-project.properties ]; then
          rm sonar-project.properties
        fi

    - name: Run tests and collect coverage
      run: |
        dotnet sonarscanner begin /k:"semester-3-backend" /o:"semester-3" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vscoveragexml.reportsPaths="**/TestResults/*.xml"
        dotnet build
        dotnet test --collect:"XPlat Code Coverage"
        dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

    - name: Publish test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: |
          **/TestResults
          !**/*.trx
