     <range source_id="3" start_line="61" end_line="61" start_column="13" end_column="89" covered="partial" />
            <range source_id="3" start_line="62" end_line="62" start_column="9" end_column="10" covered="yes" />
          </ranges>
        </function>
        <function id="9864" token="0x600001b" name="GetUserById(string)" namespace="Travelblog.Core.Services" type_name="UserService" block_coverage="0.00" line_coverage="0.00" blocks_covered="0" blocks_not_covered="6" lines_covered="0" lines_partially_covered="0" lines_not_covered="6">
          <ranges>
            <range source_id="3" start_line="65" end_line="65" start_column="9" end_column="10" covered="no" />
            <range source_id="3" start_line="66" end_line="66" start_column="13" end_column="37" covered="no" />
            <range source_id="3" start_line="67" end_line="67" start_column="13" end_column="14" covered="no" />
            <range source_id="3" start_line="68" end_line="68" start_column="17" end_column="29" covered="no" />
            <range source_id="3" start_line="70" end_line="70" start_column="13" end_column="54" covered="no" />
            <range source_id="3" start_line="71" end_line="71" start_column="9" end_column="10" covered="no" />
          </ranges>
        </function>
        <function id="9912" token="0x600001c" name="GetUserByName(string)" namespace="Travelblog.Core.Services" type_name="UserService" block_coverage="0.00" line_coverage="0.00" blocks_covered="0" blocks_not_covered="3" lines_covered="0" lines_partially_covered="0" lines_not_covered="3">
          <ranges>
            <range source_id="3" start_line="74" end_line="74" start_column="9" end_column="10" covered="no" />
            <range source_id="3" start_line="75" end_line="75" start_column="13" end_column="56" covered="no" />
            <range source_id="3" start_line="76" end_line="76" start_column="9" end_column="10" covered="no" />
          </ranges>
        </function>
        <function id="9944" token="0x600001d" name="RegisterUser(Travelblog.Core.Models.User)" namespace="Travelblog.Core.Services" type_name="UserService" block_coverage="0.00" line_coverage="0.00" blocks_covered="0" blocks_not_covered="3" lines_covered="0" lines_partially_covered="0" lines_not_covered="3">
