name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 3.1.x
      
      - name: Restore dependencies
        run: dotnet restore
      
      - name: Build the solution
        run: dotnet build --no-restore
      
      - name: Run tests and collect coverage
        run: dotnet test --no-build --collect:"XPlat Code Coverage"
      
      - name: Prepare SonarCloud Analysis
        run: dotnet tool install --global dotnet-sonarscanner
      
      - name: Begin SonarCloud Analysis
        run: dotnet sonarscanner begin /k:"semester-3-backend" /o:"semester-3" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.vstest.reportsPaths="**/TestResults/*.trx" /d:sonar.cs.opencover.reportsPaths="**/TestResults/coverage.opencover.xml"
      
      - name: Build the solution (SonarCloud)
        run: dotnet build --no-incremental
      
      - name: End SonarCloud Analysis
        run: dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
