name: .NET Deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TravelblogBackend.sln
    - name: Build
      run: dotnet build Travelblog.Api/Travelblog.Api.csproj --no-restore

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore TravelblogBackend.sln
    - name: Test
      run: dotnet test Travelblog.Unittest/Travelblog.Unittest.csproj --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - name: FTP Transfer
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: 'ftp'
        local-dir: './path/to/deploy'
        remote-dir: '/domains/i427798.luna.fhict.nl'
        port: 21
        passive: true
        secure: true

