name: SonarCloud Analysis

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      - Develop

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Download code coverage
        uses: actions/download-artifact@v3
        with:
          name: code-coverage
          path: coverage/

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.organization="semester-3"
            -Dsonar.projectKey="semester-3-backend"
            -Dsonar.cs.vscoveragexml.reportsPaths="coverage/**/*.cobertura.xml"
